[build]
  publish = "."
  command = "node inject-env.js"

[build.environment]
  NODE_VERSION = "16"

[build.processing.secrets]
  scan = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
