[build]
  publish = "."
  command = ""

[context.production]
  environment = { NODE_VERSION = "18.x" }

[context.production.environment]
  OPENAI_API_KEY = "from-netlify-ui"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
